name: Release TypeOrmGraphql

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "**/README.md"

jobs:
  build-and-publish:
    name: "Build App and Container"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Generate index files"
        run: npm run-script generate:barrels
      - name: "Build package"
        run: npm run-script build
      - run: npm publish --tag alpha
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
